// Generated by Wrangler by running `wrangler types ./backend/worker-configuration.d.ts --env-interface CloudflareBindings`

interface CloudflareBindings {
	pkginfo: KVNamespace;
	replay_check: KVNamespace;
	POW_DIFFICULTY: 16;
	POW_SIGN_KEY: string;
	ASSETS: Fetcher;
}
